### PR TITLE
deleted dis.gd stuff

### PR DESCRIPTION
**Pull request by SamomenX**
redirect to personal site idk why

### CODE REVIEW

**Comment by TheCuteFoxxy** [comment]
All of the dis.gd links are working normally for me. The base domain redirects to discord.com as intended.

**Comment by SamomenX** [comment]
https://user-images.githubusercontent.com/71833103/154856284-40f8845e-c90b-402a-8d9e-1162cc0802f6.mp4

**Comment by TheCuteFoxxy** [comment]
I will submit a PR to use my list (Should be up to date afaik)

**Comment by rydixulous** [comment]
fixed

**Pull request closed without merging**
