### PR TITLE
make readme more appealing

### PR DESCRIPTION
**Pull request by PatelN123**
Makes the readme look much more visually appealing

### CODE REVIEW

**Comment by PatelN123** [comment]
Preview:
image

**Review by arHSM — APPROVED** [review]

**Review by enygmate — APPROVED** [review]

**Comment by PrincessRavy** [comment]
where's that tagline from; is it official? 

cc @rydixulous for the wording

**Comment by PatelN123** [comment]
Yes it's official!
It's in the repos about section.
image

**Comment by rydixulous** [comment]
looks like wording wasn't changed from the current one, so I don't mind merging, as long as you approve.

**Pull request merged**
