### PR TITLE
feat: better scrollbar

### PR DESCRIPTION
**Pull request by PatelN123**
Features a better scrollbar for the site. 

Demo:
image

This scrollbar matches the resources wiki colors and is the same type as the sidebar's scrollbar.

Currently, it looks like this:
https://user-images.githubusercontent.com/79650289/158030803-f83b43e5-c429-476b-aee5-56796a48d38f.png

### CODE REVIEW

**Comment by PrincessRavy** [comment]
can we check the browser support on this?

**Comment by PatelN123** [comment]
Hey @PrincessRavy,

The webkit scrollbar supports most browsers such as Chrome, Safari and Opera. 
If the browser does not support it, it'll roll back to the default one automatically.

**Comment by PrincessRavy** [comment]
sounds good! tagging @rjt-rockx for review

**Review by rjt-rockx — COMMENTED** [review]
Any reason why we're using fixed hex codes here instead of CSS variables?
Might look off across different themes

**Comment by PatelN123** [comment]
I'm not sure what color you would like @rjt-rockx
I just went with the standard option, feel free to change it.

**Pull request closed without merging**
