### PR TITLE
Add Discord Bots Catalog to bot lists

### PR DESCRIPTION
**Pull request by angrymouse**
# New Resource PR Template

## Name of Resource:
Discord Bots Catalog
## Description of Resource:
Imagine a place where you can find discord bot for your needs. That's Discord Bots Catalog.

## A Link to the Resource: 
https://top-bots.xyz
## Discord ID(s) of the Creator(s):
@616219013969608715 @185240097728364544
This template was automatically added to your pull request. 
If you would like to adapt or remove this template to better describe your pull request, feel free to do so.

### CODE REVIEW

**Comment by rydixulous** [comment]
We don’t add bot lists to the wiki

**Comment by angrymouse** [comment]
But it's resources about discord. And then why bots.gg is added?

**Comment by angrymouse** [comment]
It is unfair to add bot.gg, although it is not official, even though it is not the most popular, but do not add other botlists!

**Comment by angrymouse** [comment]
If we don’t add bot lists to the wiki, then we should remove bots.gg

**Comment by rydixulous** [comment]
discord bots is affiliated with discord API, which is affiliated with discord. we don't add bot lists to the wiki because they usually have the same content and if not, they are super biased and not reliable. this is not for discussion.

**Comment by PrincessRavy** [comment]
In the future: if you want to discuss things prior to opening a PR, feel free to [join us on Discord](https://discord.gg/resources)

**Comment by angrymouse** [comment]
Discord API is NOT affiliated with discord. It's community-run server.
If we are talking about content uniqueness, then we should replace bot.gg with top.gg because it has MUCH more unique content.
And why is it not for discussion? Is this a "taboo"?)

**Comment by angrymouse** [comment]
> In the future: if you want to discuss things prior to opening a PR, feel free to [join us on Discord](https://discord.gg/resources)

Ok thanks

**Pull request closed without merging**
