### PR TITLE
Correctly format "Youtube" as "YouTube", "PreMid" as "PreMiD", and add Aliucord resource

### PR DESCRIPTION
**Pull request by xn-oah**
## A Link to the Resource: https://github.com/Aliucord/Aliucord

Updated formatting of some words as well.

### CODE REVIEW

**Comment by xn-oah** [comment]
I'm only assuming that adding Aliucord as a resource to this wiki is fine since there is a link to Powercord already, but if it is not allowed - apologies and will revert it.

**Comment by rydixulous** [comment]
ye powercord going EOL really made things easier for us lol
we are not going to add any new client mods to the wiki, unless discord changes their *actual* policy or gives us special permission.

**Comment by xn-oah** [comment]
wym powercord going AOL? also will remove it in a few then

**Comment by xn-oah** [comment]
EOL*

**Comment by rydixulous** [comment]
EOL = End Of Life
basically, it's gone.
now although there are other client mods, some are even better, we had powercord in before the project started, and as we progress we don't want to promote them on our site, as it gets more and more attraction.

**Comment by xn-oah** [comment]
Removed

**Pull request merged**
