### PR TITLE
Update unofficial-resources.md

### PR DESCRIPTION
**Pull request by TheCuteFoxxy**
# New Resource PR Template

## Name of Resource: 
List of dis.gd URLs

## Description of Resource:
List of all known dis.gd URLs

## A Link to the Resource: 
https://thecutefoxxy.com/discord-shortlinks

## Discord ID(s) of the Creator(s): 
641795527444529152

Update link from https://herogamers.dev/dis.gd/ (Now redirects to different, unrelated site) to https://thecutefoxxy.com/discord-shortlinks per #117

### CODE REVIEW

**Comment by SamomenX** [comment]
image
why u change tech's stuff :eyes:

**Comment by TheCuteFoxxy** [comment]
👀 Whoops, shh

**Comment by TheCuteFoxxy** [comment]
Fixed 👀

**Comment by rydixulous** [comment]
going to add your list as well, but as the original site is now back up (and has a nicer UI), we will keep it

**Pull request closed without merging**
