### PR TITLE
Capitalize Discord

### PR DESCRIPTION
**Pull request by nmsturcke**
Capitalize Discord and GitHub correctly

### CODE REVIEW

**Comment by PrincessRavy** [comment]
can you check whether this is the only occurence of lowercase discord

**Comment by nmsturcke** [comment]
> can you check whether this is the only occurence of lowercase discord

Sure

**Comment by nmsturcke** [comment]
Changed all Discord and GitHub instances that I could find

**Comment by nmsturcke** [comment]
@PrincessRavy Ready I think

**Pull request merged**
