### PR TITLE
Add myself as a maintainer

### PR DESCRIPTION
**Pull request by nmsturcke**
Add myself as a maintainer as per https://canary.discord.com/channels/807680068520378369/900704913368174683/1008816097820147742

### CODE REVIEW

**Comment by Meqativ** [comment]
link preview

**Comment by JantsoP** [comment]
Adding stuff to wiki does not make you maintainer. Please change wording to more appropriate.

Maintainers are those, who do the backend stuff and have write access to GitHub. I.e  @PrincessRavy @JantsoP @merlinfuchs

**Comment by Meqativ** [comment]
> Adding stuff to wiki does not make you maintainer. Please change wording to more appropriate.
> 
> Maintainers are those, who do the backend stuff and have write access to GitHub. I.e  @PrincessRavy @JantsoP @merlinfuchs 

also rydix who told them to do that:

**Comment by PrincessRavy** [comment]
contributor ≠ maintainer

**Comment by nmsturcke** [comment]
https://discord.com/channels/807680068520378369/900704913368174683/1008816200781938718

image

**Pull request merged**
