### PR TITLE
feat(css): Reconfigure CSS variable shades.

### PR DESCRIPTION
**Pull request by abhigyantrips**
This PR changes the default color variables as per DRW's theme. This is essential as the contrast and color of some elements throughout Docusaurus are chosen as per these specific variables.

### CODE REVIEW

**Comment by PrincessRavy** [comment]
are you able to make a visual representation of the colors that you changed, so this is easier to review?

**Comment by abhigyantrips** [comment]
There is currently no visible change on the website itself, as visible from this screenshot of the localhost.

image

But I've used [Colorbox](https://colorbox.io/) to pick the colors themselves. A table of these can be found below.

image

**Review by rjt-rockx — APPROVED** [review]
LGTM

**Comment by rydixulous** [comment]
if something break it's not my fault

**Pull request merged**
